// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxpjrvlxocsmoispaemd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4cGpydmx4b2NzbW9pc3BhZW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNjQxNzMsImV4cCI6MjA5MDg0MDE3M30.WDqta9wE0Wdw-0UCk2Z4pTG2Cy83vy_veD8yAuumo60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});